const User = require('./User');
const Wallet = require('./Wallet');
const Deposit = require('./Deposit');
const Withdrawal = require('./Withdrawal');
const Transaction = require('./Transaction');
const Trade = require('./Trade');
const Candle = require('./Candle');
const TradingAccount = require('./TradingAccount');
const BankAccount = require('./BankAccount');

User.hasOne(Wallet, { foreignKey: 'userId', as: 'wallet' });
Wallet.belongsTo(User, { foreignKey: 'userId' });
User.hasMany(Deposit, { foreignKey: 'userId' });
Deposit.belongsTo(User, { foreignKey: 'userId' });
User.hasMany(Withdrawal, { foreignKey: 'userId' });
Withdrawal.belongsTo(User, { foreignKey: 'userId' });
User.hasMany(Transaction, { foreignKey: 'userId' });
Transaction.belongsTo(User, { foreignKey: 'userId' });
User.hasMany(Trade, { foreignKey: 'userId' });
Trade.belongsTo(User, { foreignKey: 'userId' });
User.hasMany(TradingAccount, { foreignKey: 'userId', as: 'tradingAccounts' });
TradingAccount.belongsTo(User, { foreignKey: 'userId' });
User.hasMany(BankAccount, { foreignKey: 'userId', as: 'bankAccounts' });
BankAccount.belongsTo(User, { foreignKey: 'userId' });
TradingAccount.hasMany(Trade, { foreignKey: 'tradingAccountId', as: 'trades' });
Trade.belongsTo(TradingAccount, { foreignKey: 'tradingAccountId', as: 'tradingAccount' });
User.hasMany(User, { foreignKey: 'referredById', as: 'referrals' });
User.belongsTo(User, { foreignKey: 'referredById', as: 'referrer' });

module.exports = { User, Wallet, Deposit, Withdrawal, Transaction, Trade, Candle, TradingAccount, BankAccount };
