export const MARKET_GROUPS = ['POPULAR', 'CRYPTO CFD', 'ENERGIES', 'FOREX', 'INDICES', 'METALS'];

const TRADING_VIEW_OVERRIDES = {
  'BCH/EUR': 'COINBASE:BCHEUR',
  'BCH/GBP': 'COINBASE:BCHGBP',
  'BTC/EUR': 'COINBASE:BTCEUR',
  'BTC/GBP': 'COINBASE:BTCGBP',
  'ETH/EUR': 'COINBASE:ETHEUR',
  'ETH/GBP': 'COINBASE:ETHGBP',
  'LTC/EUR': 'COINBASE:LTCEUR',
  'LTC/GBP': 'COINBASE:LTCGBP',
  'ASX/AUD': 'OANDA:AU200AUD',
  'DAX/EUR': 'OANDA:DE30EUR',
  'DJI/USD': 'OANDA:US30USD',
  'ESX/EUR': 'OANDA:EU50EUR',
  'F40/EUR': 'OANDA:FR40EUR',
  'FTS/GBP': 'OANDA:UK100GBP',
  'HSI/HKD': 'OANDA:HK33HKD',
  'IBX/EUR': 'OANDA:ESPIXEUR',
  'NDX/USD': 'OANDA:NAS100USD',
  'NIK/JPY': 'OANDA:JP225USD',
  'SPX/USD': 'OANDA:SPX500USD',
  'BRN/USD': 'OANDA:BCOUSD',
  'NGC/USD': 'OANDA:NATGASUSD',
  'WTI/USD': 'OANDA:WTICOUSD',
};

const tradingViewSymbolFor = (symbol, group) => {
  if (TRADING_VIEW_OVERRIDES[symbol]) return TRADING_VIEW_OVERRIDES[symbol];
  const compact = symbol.replace('/', '');
  if (group === 'CRYPTO CFD') return `BINANCE:${compact.replace(/USD$/, 'USDT')}`;
  if (group === 'FOREX') return `FX:${compact}`;
  if (group === 'METALS') return `OANDA:${compact}`;
  return compact;
};

const make = (symbol, group, popular = false) => ({
  symbol,
  name: symbol,
  group,
  tradingViewSymbol: tradingViewSymbolFor(symbol, group),
  popular,
});

export const SYMBOLS = [
  make('ADA/USD', 'CRYPTO CFD'),
  make('APE/USD', 'CRYPTO CFD'),
  make('AXS/USD', 'CRYPTO CFD'),
  make('BAT/USD', 'CRYPTO CFD'),
  make('BCH/EUR', 'CRYPTO CFD'),
  make('BCH/GBP', 'CRYPTO CFD'),
  make('BCH/USD', 'CRYPTO CFD'),
  make('BTC/EUR', 'CRYPTO CFD'),
  make('BTC/GBP', 'CRYPTO CFD'),
  make('BTC/USD', 'CRYPTO CFD', true),
  make('CHZ/USD', 'CRYPTO CFD'),
  make('CRV/USD', 'CRYPTO CFD'),
  make('DOT/USD', 'CRYPTO CFD'),
  make('EOS/USD', 'CRYPTO CFD'),
  make('ETC/USD', 'CRYPTO CFD'),
  make('ETH/EUR', 'CRYPTO CFD'),
  make('ETH/GBP', 'CRYPTO CFD'),
  make('ETH/USD', 'CRYPTO CFD'),
  make('FIL/USD', 'CRYPTO CFD'),
  make('GAL/USD', 'CRYPTO CFD'),
  make('GMT/USD', 'CRYPTO CFD'),
  make('GRT/USD', 'CRYPTO CFD'),
  make('IMX/USD', 'CRYPTO CFD'),
  make('KNC/USD', 'CRYPTO CFD'),
  make('KSM/USD', 'CRYPTO CFD'),
  make('LPT/USD', 'CRYPTO CFD'),
  make('LRC/USD', 'CRYPTO CFD'),
  make('LTC/EUR', 'CRYPTO CFD'),
  make('LTC/GBP', 'CRYPTO CFD'),
  make('LTC/USD', 'CRYPTO CFD'),
  make('MKR/USD', 'CRYPTO CFD'),
  make('SKL/USD', 'CRYPTO CFD'),
  make('SNX/USD', 'CRYPTO CFD'),
  make('SOL/USD', 'CRYPTO CFD'),
  make('UNI/USD', 'CRYPTO CFD'),
  make('XRP/USD', 'CRYPTO CFD'),
  make('XTZ/USD', 'CRYPTO CFD'),
  make('YFI/USD', 'CRYPTO CFD'),
  make('ZEC/USD', 'CRYPTO CFD'),
  make('ZEN/USD', 'CRYPTO CFD'),
  make('ZRX/USD', 'CRYPTO CFD'),
  make('BRN/USD', 'ENERGIES'),
  make('NGC/USD', 'ENERGIES'),
  make('WTI/USD', 'ENERGIES'),
  make('AUD/CAD', 'FOREX'),
  make('AUD/CHF', 'FOREX'),
  make('AUD/JPY', 'FOREX', true),
  make('AUD/NZD', 'FOREX'),
  make('AUD/SGD', 'FOREX'),
  make('AUD/USD', 'FOREX'),
  make('CAD/CHF', 'FOREX'),
  make('CAD/JPY', 'FOREX'),
  make('CHF/JPY', 'FOREX'),
  make('EUR/AUD', 'FOREX'),
  make('EUR/CAD', 'FOREX'),
  make('EUR/CHF', 'FOREX', true),
  make('EUR/GBP', 'FOREX'),
  make('EUR/JPY', 'FOREX', true),
  make('EUR/USD', 'FOREX', true),
  make('GBP/AUD', 'FOREX'),
  make('GBP/CAD', 'FOREX'),
  make('GBP/CHF', 'FOREX'),
  make('GBP/JPY', 'FOREX'),
  make('GBP/NZD', 'FOREX'),
  make('GBP/USD', 'FOREX', true),
  make('NZD/CAD', 'FOREX'),
  make('NZD/CHF', 'FOREX'),
  make('NZD/JPY', 'FOREX'),
  make('NZD/USD', 'FOREX'),
  make('USD/CAD', 'FOREX', true),
  make('USD/CHF', 'FOREX'),
  make('USD/CNH', 'FOREX'),
  make('USD/HKD', 'FOREX'),
  make('USD/JPY', 'FOREX', true),
  make('USD/MXN', 'FOREX'),
  make('USD/SGD', 'FOREX'),
  make('USD/TRY', 'FOREX'),
  make('ASX/AUD', 'INDICES'),
  make('DAX/EUR', 'INDICES'),
  make('DJI/USD', 'INDICES'),
  make('ESX/EUR', 'INDICES'),
  make('F40/EUR', 'INDICES'),
  make('FTS/GBP', 'INDICES'),
  make('HSI/HKD', 'INDICES'),
  make('IBX/EUR', 'INDICES'),
  make('NDX/USD', 'INDICES'),
  make('NIK/JPY', 'INDICES'),
  make('SPX/USD', 'INDICES'),
  make('XAG/AUD', 'METALS'),
  make('XAG/CHF', 'METALS'),
  make('XAG/EUR', 'METALS'),
  make('XAG/GBP', 'METALS'),
  make('XAG/USD', 'METALS'),
  make('XAU/AUD', 'METALS'),
  make('XAU/CHF', 'METALS'),
  make('XAU/EUR', 'METALS'),
  make('XAU/GBP', 'METALS'),
  make('XAU/USD', 'METALS', true),
  make('XPD/USD', 'METALS'),
  make('XPT/USD', 'METALS'),
];

